# Generated by Django 4.2.5 on 2023-09-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('deporte', models.CharField(max_length=255)),
                ('descrpcion', models.CharField(max_length=255)),
                ('valorArticulo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Univalluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('tipo_univalluno', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Funcionario', 'Funcionario')], max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('codigo_estudiante', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_vencimiento', models.DateTimeField()),
                ('articulo_deportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univalluno.articulodeportivo')),
                ('univalluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univalluno.univalluno')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_pago', models.DateTimeField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univalluno.prestamo')),
            ],
        ),
    ]
